### ISSUE TITLE
[clustering] failure to discover peers when the number of instances and exposed ports is large

### ISSUE THREAD

**Issue by thampiotr** [grafana/alloy#1208]
## Issue

Alloy uses a headless service and [queries DNS for SRV records](https://github.com/grafana/alloy/blob/main/internal/alloycli/cluster_builder.go#L172) to discover peer instances, which can be used to join the cluster via [memberlist](https://github.com/hashicorp/memberlist)-based gossip protocol provided by the [ckit](https://github.com/grafana/ckit) library.

These queries were in some reported cases returning zero results, which is evidenced by a periodic logging of msg=”rejoining peers”, peers=””

The standard [Go DNS library](https://go.googlesource.com/go/+/refs/heads/master/src/net/lookup.go#493) used by Alloy was returning no results for the query.
In contrast, queries run using dig CLI utility were still returning valid results.
This indicates that there was a bug or implementation difference between Go DNS library and other DNS clients.

The DNS queries are limited in size. The query is first attempted via UDP, when the response from DNS server indicates that the message was truncated, the query is retried over TCP. 
However, even the TCP query can be truncated. This is because the TCP messages still wrap the [RFC1035 DNS](https://www.rfc-editor.org/rfc/rfc1035#section-4.2.2) message which is prefixed with a two byte length field, so the maximum length of DNS response over TCP is 65536.

When a TCP message is truncated, the Truncated flag is set to 1.
![image](https://github.com/grafana/alloy/assets/17101802/aa030c30-8937-4412-9437-cd35588f5528)

However, as seen above, there are still useful Answer RRs in the response, which can be used on the “best effort” basis by the clients.
dig does this, but Go didn’t due to this bug: https://github.com/golang/go/issues/64896 
The fix for this issue should be available in go1.23

But why are the DNS query responses so large? When Alloy cluster has, for example, 90 instances and for each of these instances, there are 10 different ports registered in the headless service, there will be 900 SRV records registered in DNS.

This is quite common - initially, the Alloy helm chart only supported one port, but [support for more ports was added later](https://github.com/grafana/alloy/commit/4a32c4477419eedabd556b723898d28d12c52d7a). 
There are 9 ports defined in the [k8s-monitoring helm](https://github.com/grafana/k8s-monitoring-helm/blob/main/charts/k8s-monitoring/values.yaml#L2055) chart.

## Proposed fixes

There are a few tasks that should be taken to resolve this issue:

```[tasklist]
### Tasks
- [ ] https://github.com/grafana/alloy/issues/1244
- [x] Improve testing in cluster peers discovery
- [x] Resolve inconsistencies in how `host:port` vs `host` is treated
- [x] Consider using A/AAAA records instead or as a fallback for the SRV records query
- [x] Improve Alloy dashboard to highlight which instances have split brain issues
- [ ] https://github.com/grafana/alloy/pull/1261
```
