### ISSUE TITLE
Update Grafana documentation, Agent-->Alloy

### ISSUE THREAD

**Issue by imatwawana** [grafana/alloy#1270]
```[tasklist]
### Tasks
- [x] Update obvious references to Agent - [90674](https://github.com/grafana/grafana/pull/90674)
- [x] Create list of remaining references for review
- [x] Assess list for further possible updates (none found)
```

**Comment by imatwawana** [comment]
@clayton-cornell 

When I search "Agent" in the Grafana docs, I get 26 results in 8 files.
When I search "agent", I get 59 results in 19 files.  
I suspect the reality falls somewhere in the middle. 

I can open a PR to work on some of the ones that seem obvious and leave it for you to review, but some of these you'd probably need to look at. I can generate a list of them for you (with some context) so you can figure out if you need to look at it. Does that work as a strategy?

**Comment by clayton-cornell** [comment]
Yes, happy to review/suggest on the changes.  Some instances of "agent" aren't always Grafana Agent... there's other agents too.. it's a bit of an overloaded term.  A list of what you found is a perfect starting point.

**Comment by imatwawana** [comment]
Okay good stuff. I'll get started next week.
