### ISSUE TITLE
Improve operational confidence

### ISSUE THREAD

**Issue by tpaschalis** [grafana/alloy#253]
We should build on our dogfooding experience to improve the operational confidence of users and help them run large-scale Grafana Agent deployments without worries.

```[tasklist]
### Tasks
- [ ] Add mixin dashboards for most common component namespaces 
- [ ] Ensure all mixin dashboards are consistent  
- [ ] Create opinionated set of alerts for grafana-agent-flow mixin 
- [ ] Write runbooks for mixin alerts 
```
