### ISSUE TITLE
Integration tests: next steps

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#322]
```[tasklist]
### Tasks
- [ ] Consider using [test containers](https://github.com/testcontainers/testcontainers-go). This could allow us to move the integration tests to drone?
- [ ] Add new tests: modules, k3d, integrations, exporter
- [ ] Consider a better way to generate Otel metrics (we currently use a demo-server and demo-client copied from [opentelemetry-collector-contrib](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo), maybe we could import it instead of copying it?)
- [ ] Consider using build tags instead of removing the integration tests via "grep -v integration-tests"
```

**Comment by ptodev** [comment]
We've been meaning to start using k8s integration tests more these days.
