### ISSUE TITLE
Drop usage of custom Prometheus exporters forks

### ISSUE THREAD

**Issue by marctc** [grafana/alloy#466]
Currently we are using replace directive in go.mod for a specific subset of [Prometheus exporters](https://github.com/grafana/agent/blob/main/go.mod#LL634).
These forks were initially created to make them work with the Agent as some of the exporters need to be configure via command line flag (like windows exporter) or don't provide a way to initialize a collector from an external package.

The main problem is that the forks get outdated at some point, making harder to keep up to date (merge upstream dependencies is not always easier) and frequently unattended.

We should work with upstream exporters to port changes there (whenever is possible). These are the following exporters that need to be addressed:

### Tasks
- [x] https://github.com/grafana/agent/issues/3415
- [x] https://github.com/grafana/agent/issues/3416
- [x] https://github.com/grafana/agent/issues/3417
- [x] https://github.com/grafana/agent/issues/3418
- [x] https://github.com/grafana/agent/issues/3419
- [x] https://github.com/grafana/agent/issues/3420
- [ ] grafana/alloy#465
- [x] https://github.com/grafana/agent/issues/3421
- [x] grafana/agent#3424
- [ ] grafana/alloy#464
- [x] grafana/agent#1845

Related grafana/agent#1230
