### ISSUE TITLE
Tracking: Community components

### ISSUE THREAD

**Issue by wildum** [grafana/alloy#992]
```[tasklist]
### Tasks
- [ ] https://github.com/grafana/alloy/issues/994
- [ ] Supervise the implementation of the first community component (datadog exporter)
- [ ] Communicate with other candidates (gcp exporter, clickhouse exporter) to offer them to write proposals
```
